const weapons = {
  simples: [
    "Club", 
    "Dagger", 
    "Greatclub", 
    "Handaxe", 
    "Javelin", 
    "Light hammer", 
    "Mace", 
    "Quarterstaff", 
    "Sickle", 
    "Spear", 
    "Crossbow, light", 
    "Dart", 
    "Shortbow", 
    "Sling"
  ],
  martials: [
    "Battleaxe",
    "Flail", 
    "Glaive", 
    "Greataxe", 
    "Greatsword", 
    "Halberd", "Lance", 
    "Longsword", 
    "Maul", 
    "Morningstar", 
    "Pike", 
    "Rapier", 
    "Scimitar", 
    "Shortsword", 
    "Trident", 
    "War pick", 
    "Warhammer", 
    "Whip", 
    "Blowgun", 
    "Crossbow, hand", 
    "Crossbow, heavy", 
    "Longbow", 
    "Net"
  ]
};